<Layer name="above_contour" status="on" srs="+proj=latlong +datum=WGS84">
  <StyleName>cliffs</StyleName>
  <StyleName>bridges-casing</StyleName>
  <StyleName>bridges-core</StyleName>
  <StyleName>trams-br-casing</StyleName>
  <StyleName>trams-br-core</StyleName>
  <StyleName>roads-br-casing</StyleName>
  <StyleName>roads-br-core</StyleName>
  <StyleName>power</StyleName>
  <StyleName>symbols</StyleName>





    <Datasource>
      &datasource-settings-otf;
    </Datasource>
</Layer>
